Abdallah:
  name: AAZAI
e:
  type: {}
  version: '1.2'
elking:
  ali: '1'
  moh: '1'
elprince:
  moh: '1'
eng:
  type: {}
  version: '1.2'
english:
  type: {}
  version: '1.2'
iperf:
  name: iperf
  type: network
  version: '1.2'
memcached:
  name: mem
  version: 3.25
sec:
  key: val
sec1: {}
test:
  Ali: '253'
  vr: '253'
test1:
  null: null
  type: ''
test2:
  type: null
test3:
  ali: null
  item: '243'
  v: ghg
  vannn: null
  vannn1: null
  vannn13: ghg
test4:
  null: null
ycsb:
  name: yahoo
  type: str
  version: '3.5'
